// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB81-Ngw-DOixiNol-74hsw1BhQZY2v3Zw',
    appId: '1:601599816160:web:21e42cd19d0723290b3b85',
    messagingSenderId: '601599816160',
    projectId: 'sit90-a4cf5',
    authDomain: 'sit90-a4cf5.firebaseapp.com',
    storageBucket: 'sit90-a4cf5.firebasestorage.app',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7FzWJXu68u4WEDoYvm-oPtr5yZRnNtVY',
    appId: '1:601599816160:android:5c4373124b11d2e20b3b85',
    messagingSenderId: '601599816160',
    projectId: 'sit90-a4cf5',
    storageBucket: 'sit90-a4cf5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB81-Ngw-DOixiNol-74hsw1BhQZY2v3Zw',
    appId: '1:601599816160:web:1a1501f061d2bef40b3b85',
    messagingSenderId: '601599816160',
    projectId: 'sit90-a4cf5',
    authDomain: 'sit90-a4cf5.firebaseapp.com',
    storageBucket: 'sit90-a4cf5.firebasestorage.app',
  );
}
